server:
  port: ${PORT:8091}
  servlet:
    context-path: /bca


spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5441/kdg_landside_db"
    username: kdg_admin
    password: kdg_admin_password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}