POST http://localhost:8180/realms/kdg/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = kdg_client &
client_secret = A3waW71ITWeQWF1QLmo9p31PoznM3s9T &
username = kdg_admin &
password = kdg_admin &
grant_type = password &
scope = openid


//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}

###
GET http://localhost:8091/api/v1/facilities/1
Authorization: Bearer {{access_token}}


###
POST http://localhost:8091/api/v1/appointments
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "sellerId":"ddf45d07-948e-4cdc-b93e-4a02e9337415",
    "truckLicensePlate":"ABC123",
    "deliveredMaterialType":"PETCOKE",
    "date":"2024-10-30",
    "preferredHour":21
}

###
POST http://localhost:8091/api/v1/requests/entrances
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "licensePlate":"ABC123",
    "materialType":"PETCOKE"
}

> {%
    client.global.set("appointmentId", response.body.appointmentId);
%}

###
GET http://localhost:8091/api/v1/appointmentManagers/2024-10-30/hourSlots/21
Authorization: Bearer {{access_token}}

###
POST http://localhost:8091/api/v1/requests/weightingbridge_passages/entrances
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "appointmentId":"0e04c872-7689-4237-8294-434a38dc161f",
  "weight":25
}
