server:
  port: ${PORT:8092}
  servlet:
    context-path: /warehouse


spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  datasource:
    url: "jdbc:postgresql://localhost:5440/kdg_warehouse_db"
    username: kdg_admin
    password: kdg_admin_password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/kdg/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/kdg